-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 19:49:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema senac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema senac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `senac` DEFAULT CHARACTER SET utf8 ;
USE `senac` ;

-- -----------------------------------------------------
-- Table `senac`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senac`.`turmas` (
  `idturmas` INT NOT NULL,
  `cod` VARCHAR(20) NOT NULL,
  `turno` VARCHAR(20) NOT NULL,
  `professores` VARCHAR(90) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idturmas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senac`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senac`.`alunos` (
  `idalunos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `nasc` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `turma` VARCHAR(45) NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  PRIMARY KEY (`idalunos`, `turmas_idturmas`),
  INDEX `fk_alunos_turmas1_idx` (`turmas_idturmas` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `senac`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senac`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senac`.`cursos` (
  `idcursos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `restricao` VARCHAR(10) NOT NULL,
  `alunos_idalunos` INT NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  PRIMARY KEY (`idcursos`),
  INDEX `fk_cursos_alunos_idx` (`alunos_idalunos` ASC) VISIBLE,
  INDEX `fk_cursos_turmas1_idx` (`turmas_idturmas` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_alunos`
    FOREIGN KEY (`alunos_idalunos`)
    REFERENCES `senac`.`alunos` (`idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `senac`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
